services:
  - type: web
    name: courierapi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: API_KEY
        sync: false
      - key: TOKEN_PATH
        sync: false
      - key: CREDENTIALS_PATH
        sync: false
      - key: LOG_PATH
        sync: false
